#!/bin/sh

DST=$1
SRC=.

for src in `find $SRC -type f`;
 do
   ETAGS=/usr/bin/etags
   case "${src}" in
     *.ad[absm]|*.[CFHMSacfhlmpsty]|*.def|*.in[cs]|*.s[as]|*.src|*.cc|\
     *.hh|*.[chy]++|*.[ch]pp|*.[chy]xx|*.pdb|*.[ch]s|*.[Cc][Oo][Bb]|\
     *.[eh]rl|*.f90|*.for|*.java|*.[cem]l|*.clisp|*.lisp|*.[Ll][Ss][Pp]|\
     [Mm]akefile*|*.pas|*.[Pp][LlMm]|*.psw|*.lm|*.pc|*.prolog|*.oak|\
     *.p[sy]|*.sch|*.scheme|*.[Ss][Cc][Mm]|*.[Ss][Mm]|*.bib|*.cl[os]|\
     *.ltx|*.sty|*.TeX|*.tex|*.texi|*.texinfo|*.txi|*.x[bp]m|*.yy|\
     *.[Ss][Qq][Ll]|*.go|*.lua)
           ${ETAGS} -o- "${src}";
           ;;
#       *)
#           FTYPE=`file ${src}`;
#           case "${FTYPE}" in
#               *script*text*)
#                   ${ETAGS} -o- "${src}";
#                   ;;
#               *text*)
#                   if head -n1 "${src}" | grep '^#!' >/dev/null 2>&1;
#                   then
#                       ${ETAGS} -o- "${src}";
#                   fi;
#                   ;;
#           esac;
#           ;;
   esac;
 done > $DST