#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

. /usr/share/bash-completion/bash_completion

alias ls='ls --color=auto'
alias psc='ps xawf -eo pid,user,cgname:50,args'
alias mc=". /usr/lib/mc/mc-wrapper.sh"
PS1='[\u@\h \W]\$ '

export EDITOR=ed

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export GO111MODULE=on

export WINEPREFIX=$HOME/win64
export WINEARCH=win64

export PATH=$PATH:$HOME/.local/bin

# Bracket/safe paste mode?
printf "\e[?2004l"

if [[ -n "`which luarocks 2>/dev/null`" ]]; then
    eval `luarocks path --bin --lua-version 5.3`
fi

# https://www.virtualbox.org/ticket/13653
CR_RENDER_FORCE_PRESENT_MAIN_THREAD=0

# Enable VritualBox Debug menu
export VBOX_GUI_DBG_ENABLED=true

# TAB with variable does what is supposed to do
shopt -s direxpand

# bcc tools
export PATH=$PATH:/usr/share/bcc/tools
export MANPATH=$MANPATH:/usr/share/bcc/man

# TPM2
export TPM2_PKCS11_STORE=/home/chri/tpm2_pkcs11_store
alias tpm2pkcs11-tool="pkcs11-tool --module /usr/lib/pkcs11/libtpm2_pkcs11.so"

# ncdu, some color please :-)
alias ncdu="ncdu --color dark"

# kubectl completion
source <(kubectl completion bash)

function path_remove {
  # Delete path by parts so we can never accidentally remove sub paths
  PATH=${PATH//":$1:"/":"} # delete any instances in the middle
  PATH=${PATH/#"$1:"/} # delete any instance at the beginning
  PATH=${PATH/%":$1"/} # delete any instance in the at the end
}

if [[ ! -z $DISPLAY ]]; then
    # Python virtualenv setup
    path_remove /home/chri/python-virtual-environments/astro/bin
    export WORKON_HOME=~/python-virtual-environments
    source /usr/bin/virtualenvwrapper_lazy.sh
    workon astro
fi

