pulsemixer  --get-volume --id 0
xdg_menu --format awesome --root-menu /etc/xdg/menus/arch-applications.menu >~/.config/awesome/archmenu.lua
setxkbmap -layout 'us(intl)'
xmodmap ~/.Xmodmap
/usr/bin/dispwin -I /home/chri/icc/current.icc
# Moved to a service file 
# udiskie --tray --no-automount &
# /usr/bin/roccateventhandler &
systemctl --user import-environment
systemctl --user start x11on.target
awesome -c /home/chri/.config/awesome/rc.lua
systemctl --user start x11off.target

