#!/usr/bin/env python

#
# crappy_cropper: crops all the tiff images on the command line to the
# smallest dimension. Used for mosaic of images generated by
# autostakkeret and such. Prerequisites: "pip install tifffile".
#

import re
import sys
import tifffile


PARSE_NAME = re.compile(r"^(.+)(\.[^.]+)$")
w = 1000000
h = 1000000
for name in sys.argv[1:]:
    im = tifffile.imread(name)
    h = min(h, im.shape[0])
    w = min(w, im.shape[1])
    print("read:", name, im.shape, im.dtype)
for name in sys.argv[1:]:
    parts = PARSE_NAME.match(name)
    if parts is None:
        raise ValueError("Invalid filename")
    new_name = parts[1] + "_crop" + parts[2]
    im = tifffile.imread(name)
    y = (im.shape[0] - h) // 2
    x = (im.shape[1] - w) // 2
    new_image = im[y:(y + h), x:(x + w), :]
    print("write:", new_name, new_image.shape, new_image.dtype)
    tifffile.imwrite(new_name, new_image, photometric='rgb')
